name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Assure-toi que le clone est complet pour une analyse correcte

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          sonar-project-properties: sonar-project.properties  # Spécifie le fichier de configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisé pour récupérer les informations PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ton token SonarQube/SonarCloud
